BEGIN;
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(1,'Legend_of_Blue_Eyes_White_Dragon','Legend of Blue Eyes White Dragon','db/data/development/artworks/Legend_of_Blue_Eyes_White_Dragon/Legend_of_Blue_Eyes_White_Dragon/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(2,'Metal_Raiders','Metal Raiders','db/data/development/artworks/Metal_Raiders/Metal_Raiders/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(3,'Spell_Ruler','Spell Ruler','db/data/development/artworks/Spell_Ruler/Spell_Ruler/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(4,'Pharaoh%27s_Servant','Pharaoh''s Servant','db/data/development/artworks/Pharaoh%27s_Servant/Pharaoh%27s_Servant/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(5,'Labyrinth_of_Nightmare','Labyrinth of Nightmare','db/data/development/artworks/Labyrinth_of_Nightmare/Labyrinth_of_Nightmare/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(6,'Legacy_of_Darkness','Legacy of Darkness','db/data/development/artworks/Legacy_of_Darkness/Legacy_of_Darkness/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(7,'Pharaonic_Guardian','Pharaonic Guardian','db/data/development/artworks/Pharaonic_Guardian/Pharaonic_Guardian/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(8,'Magician%27s_Force','Magician''s Force','db/data/development/artworks/Magician%27s_Force/Magician%27s_Force/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(9,'Dark_Crisis','Dark Crisis','db/data/development/artworks/Dark_Crisis/Dark_Crisis/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(10,'Invasion_of_Chaos','Invasion of Chaos','db/data/development/artworks/Invasion_of_Chaos/Invasion_of_Chaos/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(11,'Ancient_Sanctuary','Ancient Sanctuary','db/data/development/artworks/Ancient_Sanctuary/Ancient_Sanctuary/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(12,'Flaming_Eternity','Flaming Eternity','db/data/development/artworks/Flaming_Eternity/Flaming_Eternity/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(13,'The_Lost_Millennium','The Lost Millennium','db/data/development/artworks/The_Lost_Millennium/The_Lost_Millennium/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(14,'Elemental_Energy','Elemental Energy','db/data/development/artworks/Elemental_Energy/Elemental_Energy/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(15,'Enemy_of_Justice','Enemy of Justice','db/data/development/artworks/Enemy_of_Justice/Enemy_of_Justice/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(16,'Power_of_the_Duelist','Power of the Duelist','db/data/development/artworks/Power_of_the_Duelist/Power_of_the_Duelist/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(17,'Cyberdark_Impact','Cyberdark Impact','db/data/development/artworks/Cyberdark_Impact/Cyberdark_Impact/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(18,'Strike_of_Neos','Strike of Neos','db/data/development/artworks/Strike_of_Neos/Strike_of_Neos/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(19,'Tactical_Evolution','Tactical Evolution','db/data/development/artworks/Tactical_Evolution/Tactical_Evolution/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(20,'Phantom_Darkness','Phantom Darkness','db/data/development/artworks/Phantom_Darkness/Phantom_Darkness/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(21,'The_Duelist_Genesis','The Duelist Genesis','db/data/development/artworks/The_Duelist_Genesis/The_Duelist_Genesis/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(22,'Raging_Battle','Raging Battle','db/data/development/artworks/Raging_Battle/Raging_Battle/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(23,'Ancient_Prophecy','Ancient Prophecy','db/data/development/artworks/Ancient_Prophecy/Ancient_Prophecy/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(24,'Stardust_Overdrive','Stardust Overdrive','db/data/development/artworks/Stardust_Overdrive/Stardust_Overdrive/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(25,'The_Shining_Darkness','The Shining Darkness','db/data/development/artworks/The_Shining_Darkness/The_Shining_Darkness/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(26,'Starstrike_Blast','Starstrike Blast','db/data/development/artworks/Starstrike_Blast/Starstrike_Blast/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(27,'Extreme_Victory','Extreme Victory','db/data/development/artworks/Extreme_Victory/Extreme_Victory/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(28,'Photon_Shockwave','Photon Shockwave','db/data/development/artworks/Photon_Shockwave/Photon_Shockwave/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(29,'Order_of_Chaos','Order of Chaos','db/data/development/artworks/Order_of_Chaos/Order_of_Chaos/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(30,'Galactic_Overlord','Galactic Overlord','db/data/development/artworks/Galactic_Overlord/Galactic_Overlord/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(31,'Return_of_the_Duelist','Return of the Duelist','db/data/development/artworks/Return_of_the_Duelist/Return_of_the_Duelist/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(32,'Abyss_Rising','Abyss Rising','db/data/development/artworks/Abyss_Rising/Abyss_Rising/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(33,'Cosmo_Blazer','Cosmo Blazer','db/data/development/artworks/Cosmo_Blazer/Cosmo_Blazer/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(34,'Lord_of_the_Tachyon_Galaxy','Lord of the Tachyon Galaxy','db/data/development/artworks/Lord_of_the_Tachyon_Galaxy/Lord_of_the_Tachyon_Galaxy/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(35,'Judgment_of_the_Light','Judgment of the Light','db/data/development/artworks/Judgment_of_the_Light/Judgment_of_the_Light/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(36,'Shadow_Specters','Shadow Specters','db/data/development/artworks/Shadow_Specters/Shadow_Specters/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(37,'Legacy_of_the_Valiant','Legacy of the Valiant','db/data/development/artworks/Legacy_of_the_Valiant/Legacy_of_the_Valiant/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(38,'Primal_Origin','Primal Origin','db/data/development/artworks/Primal_Origin/Primal_Origin/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(39,'Duelist_Alliance','Duelist Alliance','db/data/development/artworks/Duelist_Alliance/Duelist_Alliance/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(40,'The_New_Challengers','The New Challengers','db/data/development/artworks/The_New_Challengers/The_New_Challengers/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(41,'Secrets_of_Eternity','Secrets of Eternity','db/data/development/artworks/Secrets_of_Eternity/Secrets_of_Eternity/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(42,'Crossed_Souls','Crossed Souls','db/data/development/artworks/Crossed_Souls/Crossed_Souls/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(43,'Breakers_of_Shadow','Breakers of Shadow','db/data/development/artworks/Breakers_of_Shadow/Breakers_of_Shadow/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(44,'Shining_Victories','Shining Victories','db/data/development/artworks/Shining_Victories/Shining_Victories/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(45,'Invasion:_Vengeance','Invasion: Vengeance','db/data/development/artworks/Invasion:_Vengeance/Invasion:_Vengeance/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(46,'Raging_Tempest','Raging Tempest','db/data/development/artworks/Raging_Tempest/Raging_Tempest/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(47,'Rise_of_Destiny','Rise of Destiny','db/data/development/artworks/Rise_of_Destiny/Rise_of_Destiny/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(48,'Cybernetic_Revolution','Cybernetic Revolution','db/data/development/artworks/Cybernetic_Revolution/Cybernetic_Revolution/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(49,'Shadow_of_Infinity','Shadow of Infinity','db/data/development/artworks/Shadow_of_Infinity/Shadow_of_Infinity/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(50,'Force_of_the_Breaker','Force of the Breaker','db/data/development/artworks/Force_of_the_Breaker/Force_of_the_Breaker/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(51,'Light_of_Destruction','Light of Destruction','db/data/development/artworks/Light_of_Destruction/Light_of_Destruction/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(52,'Crossroads_of_Chaos','Crossroads of Chaos','db/data/development/artworks/Crossroads_of_Chaos/Crossroads_of_Chaos/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(53,'Absolute_Powerforce','Absolute Powerforce','db/data/development/artworks/Absolute_Powerforce/Absolute_Powerforce/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(54,'Storm_of_Ragnarok','Storm of Ragnarok','db/data/development/artworks/Storm_of_Ragnarok/Storm_of_Ragnarok/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(55,'Soul_of_the_Duelist','Soul of the Duelist','db/data/development/artworks/Soul_of_the_Duelist/Soul_of_the_Duelist/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(56,'Gladiator%27s_Assault','Gladiator''s Assault','db/data/development/artworks/Gladiator%27s_Assault/Gladiator%27s_Assault/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(57,'Crimson_Crisis','Crimson Crisis','db/data/development/artworks/Crimson_Crisis/Crimson_Crisis/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(58,'Duelist_Revolution','Duelist Revolution','db/data/development/artworks/Duelist_Revolution/Duelist_Revolution/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(59,'Clash_of_Rebellions','Clash of Rebellions','db/data/development/artworks/Clash_of_Rebellions/Clash_of_Rebellions/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(60,'Dimension_of_Chaos','Dimension of Chaos','db/data/development/artworks/Dimension_of_Chaos/Dimension_of_Chaos/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(61,'The_Dark_Illusion','The Dark Illusion','db/data/development/artworks/The_Dark_Illusion/The_Dark_Illusion/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(62,'Maximum_Crisis','Maximum Crisis','db/data/development/artworks/Maximum_Crisis/Maximum_Crisis/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(63,'Generation_Force','Generation Force','db/data/development/artworks/Generation_Force/Generation_Force/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(64,'Vol.1','Vol.1','db/data/development/artworks/Vol.1/Vol.1/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(65,'Vol.2','Vol.2','db/data/development/artworks/Vol.2/Vol.2/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(66,'Booster_1','Booster 1','db/data/development/artworks/Booster_1/Booster_1/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(67,'Booster_2','Booster 2','db/data/development/artworks/Booster_2/Booster_2/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(68,'Booster_3','Booster 3','db/data/development/artworks/Booster_3/Booster_3/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(69,'Booster_4','Booster 4','db/data/development/artworks/Booster_4/Booster_4/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(70,'Booster_5','Booster 5','db/data/development/artworks/Booster_5/Booster_5/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(71,'Booster_6','Booster 6','db/data/development/artworks/Booster_6/Booster_6/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(72,'Booster_7','Booster 7','db/data/development/artworks/Booster_7/Booster_7/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(73,'Vol.4','Vol.4','db/data/development/artworks/Vol.4/Vol.4/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(74,'Vol.3','Vol.3','db/data/development/artworks/Vol.3/Vol.3/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(75,'Vol.5','Vol.5','db/data/development/artworks/Vol.5/Vol.5/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(76,'Vol.6','Vol.6','db/data/development/artworks/Vol.6/Vol.6/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(77,'Vol.7','Vol.7','db/data/development/artworks/Vol.7/Vol.7/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(78,'Magic_Ruler_(Japanese)','Magic Ruler','db/data/development/artworks/Magic_Ruler_(Japanese)/Magic_Ruler_(Japanese)/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(79,'Curse_of_Anubis_(set)','Curse of Anubis','db/data/development/artworks/Curse_of_Anubis_(set)/Curse_of_Anubis_(set)/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(80,'Thousand_Eyes_Bible','Thousand Eyes Bible','db/data/development/artworks/Thousand_Eyes_Bible/Thousand_Eyes_Bible/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(81,'Spell_of_Mask','Spell of Mask','db/data/development/artworks/Spell_of_Mask/Spell_of_Mask/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(82,'Labyrinth_of_Nightmare_(Japanese)','Labyrinth of Nightmare','db/data/development/artworks/Labyrinth_of_Nightmare_(Japanese)/Labyrinth_of_Nightmare_(Japanese)/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(83,'Struggle_of_Chaos','Struggle of Chaos','db/data/development/artworks/Struggle_of_Chaos/Struggle_of_Chaos/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(84,'Mythological_Age','Mythological Age','db/data/development/artworks/Mythological_Age/Mythological_Age/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(85,'The_New_Ruler','The New Ruler','db/data/development/artworks/The_New_Ruler/The_New_Ruler/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(86,'Power_of_the_Guardian','Power of the Guardian','db/data/development/artworks/Power_of_the_Guardian/Power_of_the_Guardian/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(87,'Invader_of_Darkness_(set)','Invader of Darkness','db/data/development/artworks/Invader_of_Darkness_(set)/Invader_of_Darkness_(set)/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(88,'The_Sanctuary_in_the_Sky_(set)','The Sanctuary in the Sky','db/data/development/artworks/The_Sanctuary_in_the_Sky_(set)/The_Sanctuary_in_the_Sky_(set)/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(89,'Pharaoh%27s_Inheritance','Pharaoh''s Inheritance','db/data/development/artworks/Pharaoh%27s_Inheritance/Pharaoh%27s_Inheritance/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(90,'Pharaoh%27s_Servant_(Japanese)','Pharaoh''s Servant','db/data/development/artworks/Pharaoh%27s_Servant_(Japanese)/Pharaoh%27s_Servant_(Japanese)/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(91,'Pharaonic_Guardian_(Japanese)','Pharaonic Guardian','db/data/development/artworks/Pharaonic_Guardian_(Japanese)/Pharaonic_Guardian_(Japanese)/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(92,'Threat_of_the_Dark_Demon_World','Threat of the Dark Demon World','db/data/development/artworks/Threat_of_the_Dark_Demon_World/Threat_of_the_Dark_Demon_World/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(93,'Controller_of_Chaos','Controller of Chaos','db/data/development/artworks/Controller_of_Chaos/Controller_of_Chaos/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(94,'Advent_of_Union','Advent of Union','db/data/development/artworks/Advent_of_Union/Advent_of_Union/.png',300);
INSERT INTO booster_packs(id,db_name,name,image_path,cost) VALUES(95,'Champion_of_Black_Magic','Champion of Black Magic','db/data/development/artworks/Champion_of_Black_Magic/Champion_of_Black_Magic/.png',300);
COMMIT;
