require 'spec_helper'
require 'fileutils'

module YugiohX2Spec
  module SyncForbiddenLimitedListsSpec
    class Helper
      def self.run_job(absolute_path)
        job = YugiohX2Lib::Jobs::SyncForbiddenLimitedLists.new
        job.sync(absolute_path)
      end
    end

    RSpec.describe YugiohX2Lib::Jobs::SyncForbiddenLimitedLists do
      let(:jun_url) { "spec/samples/Forbidden_Limited_List_Jun_2017.html" }
      let(:expected_data) do
        [{"card_id"=>318, "limited_status"=>"Forbidden"},
         {"card_id"=>459, "limited_status"=>"Limited"},
         {"card_id"=>485, "limited_status"=>"Semi-Limited"},
         {"card_id"=>657, "limited_status"=>"Limited"},
         {"card_id"=>740, "limited_status"=>"Limited"},
         {"card_id"=>848, "limited_status"=>"Forbidden"},
         {"card_id"=>862, "limited_status"=>"Limited"},
         {"card_id"=>868, "limited_status"=>"Limited"},
         {"card_id"=>882, "limited_status"=>"Limited"},
         {"card_id"=>957, "limited_status"=>"Limited"},
         {"card_id"=>986, "limited_status"=>"Limited"},
         {"card_id"=>1031, "limited_status"=>"Forbidden"},
         {"card_id"=>1051, "limited_status"=>"Forbidden"},
         {"card_id"=>1086, "limited_status"=>"Semi-Limited"},
         {"card_id"=>1093, "limited_status"=>"Forbidden"},
         {"card_id"=>1094, "limited_status"=>"Semi-Limited"},
         {"card_id"=>1130, "limited_status"=>"Forbidden"},
         {"card_id"=>1153, "limited_status"=>"Semi-Limited"},
         {"card_id"=>1154, "limited_status"=>"Forbidden"},
         {"card_id"=>1166, "limited_status"=>"Semi-Limited"},
         {"card_id"=>1227, "limited_status"=>"Forbidden"},
         {"card_id"=>1236, "limited_status"=>"Limited"},
         {"card_id"=>1293, "limited_status"=>"Forbidden"},
         {"card_id"=>1325, "limited_status"=>"Limited"},
         {"card_id"=>1376, "limited_status"=>"Forbidden"},
         {"card_id"=>1560, "limited_status"=>"Forbidden"},
         {"card_id"=>1568, "limited_status"=>"Forbidden"},
         {"card_id"=>1699, "limited_status"=>"Limited"},
         {"card_id"=>1713, "limited_status"=>"Limited"},
         {"card_id"=>1804, "limited_status"=>"Semi-Limited"},
         {"card_id"=>1875, "limited_status"=>"Semi-Limited"},
         {"card_id"=>1904, "limited_status"=>"Limited"},
         {"card_id"=>1924, "limited_status"=>"Forbidden"},
         {"card_id"=>1975, "limited_status"=>"Forbidden"},
         {"card_id"=>1984, "limited_status"=>"Limited"},
         {"card_id"=>2059, "limited_status"=>"Limited"},
         {"card_id"=>2067, "limited_status"=>"Limited"},
         {"card_id"=>2105, "limited_status"=>"Forbidden"},
         {"card_id"=>2147, "limited_status"=>"Forbidden"},
         {"card_id"=>2190, "limited_status"=>"Limited"},
         {"card_id"=>2194, "limited_status"=>"Semi-Limited"},
         {"card_id"=>2368, "limited_status"=>"Forbidden"},
         {"card_id"=>2375, "limited_status"=>"Limited"},
         {"card_id"=>2409, "limited_status"=>"Forbidden"},
         {"card_id"=>2423, "limited_status"=>"Limited"},
         {"card_id"=>2496, "limited_status"=>"Forbidden"},
         {"card_id"=>2506, "limited_status"=>"Limited"},
         {"card_id"=>2545, "limited_status"=>"Limited"},
         {"card_id"=>2562, "limited_status"=>"Limited"},
         {"card_id"=>2579, "limited_status"=>"Forbidden"},
         {"card_id"=>2584, "limited_status"=>"Limited"},
         {"card_id"=>2636, "limited_status"=>"Limited"},
         {"card_id"=>2717, "limited_status"=>"Limited"},
         {"card_id"=>2734, "limited_status"=>"Forbidden"},
         {"card_id"=>2775, "limited_status"=>"Forbidden"},
         {"card_id"=>2881, "limited_status"=>"Limited"},
         {"card_id"=>2995, "limited_status"=>"Limited"},
         {"card_id"=>3100, "limited_status"=>"Forbidden"},
         {"card_id"=>3182, "limited_status"=>"Limited"},
         {"card_id"=>3271, "limited_status"=>"Forbidden"},
         {"card_id"=>3442, "limited_status"=>"Forbidden"},
         {"card_id"=>3448, "limited_status"=>"Limited"},
         {"card_id"=>3641, "limited_status"=>"Forbidden"},
         {"card_id"=>3674, "limited_status"=>"Forbidden"},
         {"card_id"=>3788, "limited_status"=>"Semi-Limited"},
         {"card_id"=>3880, "limited_status"=>"Limited"},
         {"card_id"=>3899, "limited_status"=>"Limited"},
         {"card_id"=>3918, "limited_status"=>"Limited"},
         {"card_id"=>3920, "limited_status"=>"Limited"},
         {"card_id"=>3934, "limited_status"=>"Limited"},
         {"card_id"=>3998, "limited_status"=>"Semi-Limited"},
         {"card_id"=>4023, "limited_status"=>"Limited"},
         {"card_id"=>4033, "limited_status"=>"Limited"},
         {"card_id"=>4170, "limited_status"=>"Forbidden"},
         {"card_id"=>4289, "limited_status"=>"Limited"},
         {"card_id"=>4365, "limited_status"=>"Forbidden"},
         {"card_id"=>4366, "limited_status"=>"Forbidden"},
         {"card_id"=>4392, "limited_status"=>"Forbidden"},
         {"card_id"=>4400, "limited_status"=>"Limited"},
         {"card_id"=>4402, "limited_status"=>"Limited"},
         {"card_id"=>4505, "limited_status"=>"Limited"},
         {"card_id"=>4578, "limited_status"=>"Limited"},
         {"card_id"=>4615, "limited_status"=>"Limited"},
         {"card_id"=>4665, "limited_status"=>"Limited"},
         {"card_id"=>4677, "limited_status"=>"Forbidden"},
         {"card_id"=>4732, "limited_status"=>"Forbidden"},
         {"card_id"=>4750, "limited_status"=>"Forbidden"},
         {"card_id"=>4839, "limited_status"=>"Forbidden"},
         {"card_id"=>4855, "limited_status"=>"Limited"},
         {"card_id"=>4862, "limited_status"=>"Limited"},
         {"card_id"=>4989, "limited_status"=>"Forbidden"},
         {"card_id"=>5029, "limited_status"=>"Limited"},
         {"card_id"=>5033, "limited_status"=>"Forbidden"},
         {"card_id"=>5068, "limited_status"=>"Forbidden"},
         {"card_id"=>5131, "limited_status"=>"Limited"},
         {"card_id"=>5133, "limited_status"=>"Forbidden"},
         {"card_id"=>5152, "limited_status"=>"Forbidden"},
         {"card_id"=>5153, "limited_status"=>"Forbidden"},
         {"card_id"=>5300, "limited_status"=>"Semi-Limited"},
         {"card_id"=>5323, "limited_status"=>"Limited"},
         {"card_id"=>5330, "limited_status"=>"Limited"},
         {"card_id"=>5352, "limited_status"=>"Limited"},
         {"card_id"=>5365, "limited_status"=>"Limited"},
         {"card_id"=>5455, "limited_status"=>"Forbidden"},
         {"card_id"=>5624, "limited_status"=>"Semi-Limited"},
         {"card_id"=>5635, "limited_status"=>"Limited"},
         {"card_id"=>5636, "limited_status"=>"Limited"},
         {"card_id"=>5706, "limited_status"=>"Forbidden"},
         {"card_id"=>5735, "limited_status"=>"Limited"},
         {"card_id"=>5783, "limited_status"=>"Forbidden"},
         {"card_id"=>5787, "limited_status"=>"Forbidden"},
         {"card_id"=>5834, "limited_status"=>"Forbidden"},
         {"card_id"=>6002, "limited_status"=>"Forbidden"},
         {"card_id"=>6008, "limited_status"=>"Forbidden"},
         {"card_id"=>6062, "limited_status"=>"Forbidden"},
         {"card_id"=>6064, "limited_status"=>"Limited"},
         {"card_id"=>6171, "limited_status"=>"Limited"},
         {"card_id"=>6258, "limited_status"=>"Limited"},
         {"card_id"=>6326, "limited_status"=>"Limited"},
         {"card_id"=>6371, "limited_status"=>"Limited"},
         {"card_id"=>6385, "limited_status"=>"Forbidden"},
         {"card_id"=>6399, "limited_status"=>"Limited"},
         {"card_id"=>6402, "limited_status"=>"Limited"},
         {"card_id"=>6430, "limited_status"=>"Limited"},
         {"card_id"=>6433, "limited_status"=>"Limited"},
         {"card_id"=>6448, "limited_status"=>"Forbidden"},
         {"card_id"=>6480, "limited_status"=>"Limited"},
         {"card_id"=>6481, "limited_status"=>"Limited"},
         {"card_id"=>6484, "limited_status"=>"Limited"},
         {"card_id"=>6507, "limited_status"=>"Limited"},
         {"card_id"=>6578, "limited_status"=>"Forbidden"},
         {"card_id"=>6582, "limited_status"=>"Limited"},
         {"card_id"=>6652, "limited_status"=>"Limited"},
         {"card_id"=>6765, "limited_status"=>"Forbidden"},
         {"card_id"=>6896, "limited_status"=>"Forbidden"},
         {"card_id"=>6943, "limited_status"=>"Forbidden"},
         {"card_id"=>6955, "limited_status"=>"Limited"},
         {"card_id"=>7023, "limited_status"=>"Forbidden"},
         {"card_id"=>7043, "limited_status"=>"Forbidden"},
         {"card_id"=>7046, "limited_status"=>"Limited"},
         {"card_id"=>7069, "limited_status"=>"Limited"},
         {"card_id"=>7072, "limited_status"=>"Limited"},
         {"card_id"=>7186, "limited_status"=>"Limited"},
         {"card_id"=>7215, "limited_status"=>"Forbidden"},
         {"card_id"=>7437, "limited_status"=>"Forbidden"},
         {"card_id"=>7463, "limited_status"=>"Semi-Limited"},
         {"card_id"=>7482, "limited_status"=>"Forbidden"},
         {"card_id"=>7494, "limited_status"=>"Forbidden"},
         {"card_id"=>7635, "limited_status"=>"Limited"},
         {"card_id"=>7680, "limited_status"=>"Limited"},
         {"card_id"=>7720, "limited_status"=>"Forbidden"},
         {"card_id"=>7723, "limited_status"=>"Forbidden"},
         {"card_id"=>7757, "limited_status"=>"Limited"},
         {"card_id"=>7820, "limited_status"=>"Forbidden"},
         {"card_id"=>7863, "limited_status"=>"Limited"},
         {"card_id"=>7921, "limited_status"=>"Forbidden"},
         {"card_id"=>7965, "limited_status"=>"Semi-Limited"},
         {"card_id"=>7974, "limited_status"=>"Forbidden"},
         {"card_id"=>7988, "limited_status"=>"Forbidden"},
         {"card_id"=>8081, "limited_status"=>"Limited"},
         {"card_id"=>8088, "limited_status"=>"Limited"},
         {"card_id"=>8109, "limited_status"=>"Forbidden"},
         {"card_id"=>8155, "limited_status"=>"Forbidden"},
         {"card_id"=>8181, "limited_status"=>"Limited"},
         {"card_id"=>8301, "limited_status"=>"Forbidden"},
         {"card_id"=>8353, "limited_status"=>"Limited"},
         {"card_id"=>8393, "limited_status"=>"Forbidden"},
         {"card_id"=>8426, "limited_status"=>"Forbidden"},
         {"card_id"=>8511, "limited_status"=>"Limited"},
         {"card_id"=>8567, "limited_status"=>"Forbidden"},
         {"card_id"=>8622, "limited_status"=>"Forbidden"},
         {"card_id"=>8630, "limited_status"=>"Semi-Limited"},
         {"card_id"=>8679, "limited_status"=>"Forbidden"},
         {"card_id"=>8813, "limited_status"=>"Forbidden"},
         {"card_id"=>8902, "limited_status"=>"Semi-Limited"}]
      end

      before :each do
        YugiohX2Lib::DBUtils.seed("db/seeds/cards.data.sql")
      end

      it "syncs the list" do
        Helper.run_job(jun_url)

        expect(YugiohX2::ForbiddenLimitedList.count).to eq(1)
        forbidden_limited_list = YugiohX2::ForbiddenLimitedList.first

        expect(forbidden_limited_list.effective_from).to eq(Date.parse("2017-06-12"))
        expect(forbidden_limited_list.forbidden_limited_list_cards.count).to eq(175)

        data = JSON.parse(forbidden_limited_list.forbidden_limited_list_cards.to_json(except: [:id, :forbidden_limited_list_id]))
        expect(data).to match_array(expected_data)
      end
    end
  end
end
