GET:
  /healthcheck: YugiohX2::BaseController
  /users/get: YugiohX2::UsersController
  /users/cards: YugiohX2::UsersController
  /cards/db_names: YugiohX2::CardsController
  /cards/get: YugiohX2::CardsController

POST:
  /login: YugiohX2::AccountsController
  /logout: YugiohX2::AccountsController
  /shops/purchase: YugiohX2::ShopsController
  /shops/password_machine: YugiohX2::ShopsController